<h2><?=$this->escape($this->title)?></h2>
<div>
<?php
	$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
	echo $this->form('forms_Search',
		array('action' => $this->url( array('action' => 'search' ) ), 'method' => 'get'),
		$this->textBox('q', $this->query,
			array('style' => 'width:400px; padding:2px;'), array('size' => '56')
		).
		$this->submitButton('submitSearch', 'Search Litters', array(), array('style' => 'margin-top: 1px;')).
		( $this->canSearch ? ' <a href="'.$this->url ( array ('controller' => 'search', 'action' => 'view', 'subject' => Searches::SUBJECT_LITTER ), null, true ).'">advanced</a>' : '')
		
	);
?>
</div>
<br />
<?php if ($this->search_error != '') : ?>
<div class="error"><?=$this->search_error?></div>
<?php elseif ($this->query != '') : ?>
<h3><?=$this->paginator->getAdapter ()->count ()?> results found for <em><?=$this->escape ( $this->query )?></em></h3>

<?php if ($this->paginator->count ()) : ?>
<table class="expand sortable">
	<tr>
		<th>Litter</th>
		<th>Born On</th>
		<th>Weaned On</th>
		<th>Alive Pups</th>
		<th>Strain</th>
		<th>Modifed on</th>
	</tr>
<?php foreach ( $this->paginator as $litter ) : ?>
<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'view', 'id' => $litter['id'] ), null, true )?>"><?=$this->escape ( $litter['assigned_id'] )?></a></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($litter['born_on']) )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($litter['weaned_on']) )?></td>
		<td><?=$this->escape ( $litter['alive_pups'] )?></td>
		<td><?=$this->escape ( $litter['strain_name'] )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($litter['lastmodified']) )?></td>
	</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
<?=$this->paginationControl ( $this->paginator, 'Elastic', 'paginator.phtml', array('q' => $this->query) )?>
<?php endif; ?>