<h2><?=$this->escape($this->title)?></h2>
<div>
<?php
	$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
	echo $this->form('forms_Search',
		array('action' => $this->url( array('action' => 'search' ) ), 'method' => 'get'),
		$this->textBox('q', $this->query,
			array('style' => 'width:400px; padding:2px;'), array('size' => '56')
		).
		$this->submitButton('submitSearch', 'Search Mouse', array(), array('style' => 'margin-top: 1px;')).
		( $this->canSearch ? ' <a href="'.$this->url ( array ('controller' => 'search', 'action' => 'view', 'subject' => Searches::SUBJECT_MOUSE ), null, true ).'">advanced</a>' : '')
		
	);
?>
</div>
<br />
<?php if ($this->search_error != '') : ?>
<div class="error"><?=$this->search_error?></div>
<?php elseif ($this->query != '') : ?>
<h3><?=$this->paginator->getAdapter ()->count ()?> results found for <em><?=$this->escape ( $this->query )?></em></h3>

<?php if ($this->paginator->count ()) : ?>
<table class="expand sortable">
	<tr>
		<th>Mouse</th>
		<th>Sex</th>
		<th>Alive</th>
		<th>Status</th>
		<th>Strain</th>
		<th>Genotype</th>
		<th>DOB</th>
	</tr>
<?php foreach ( $this->paginator as $mouse ) : ?>
<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'view', 'id' => $mouse['id'] ), null, true )?>"><?=$this->escape ( $mouse['assigned_id'] )?></a></td>
		<td><?=$this->escape ( $mouse['sex'] )?></td>
		<td><?=$this->escape ( $mouse['is_alive'] ? 'Y' : 'N' )?></td>
		<td><?=$this->escape ( $mouse['status'] )?></td>
		<td><a href="<?=$this->url ( array ('controller' => 'strain', 'action' => 'view', 'id' => $mouse['strain_id'] ), null, true )?>"><?=$this->escape ( $mouse['strain_name'] )?></a></td>
		<td><?=$this->escape ( $mouse['genotype'] )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($mouse['born_on']) )?></td>
	</tr>
<?php endforeach; ?>
</table>
<?php endif;?>
<?=$this->paginationControl ( $this->paginator, 'Elastic', 'paginator.phtml', array('q' => $this->query) )?>
<?php endif;?>