<h2><?=$this->escape($this->title)?></h2>
<div class="noprint">
<?php
	$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
	echo $this->form('forms_Search',
		array('action' => $this->url( array('action' => 'search' ) ), 'method' => 'get'),
		$this->textBox('q', "",
			array('style' => 'width:400px; padding:2px;'), array('size' => '56')
		).
		$this->submitButton('submitSearch', 'Search Weaning Cages', array(), array('style' => 'margin-top: 1px;')).
		( $this->canSearch ? ' <a href="'.$this->url ( array ('controller' => 'search', 'action' => 'view', 'subject' => Searches::SUBJECT_WEANING_CAGE ), null, true ).'">advanced</a>' : '')
		
	);
?>
</div>
<br />
<p style="color:gray">New weaning cages are created on <a href="<?=$this->url ( array ('controller' => 'litter' ), null, true )?>">litter pages</a>.</p>

<h3>Recently modified weaning cages</h3>
<table class="expand sortable">
	<tr>
		<th>Cage</th>
		<th>Litter</th>
		<th>Sex</th>
		<th>Weaned on</th>
		<th>Modifed on</th>
	</tr>
<?php foreach ( $this->recently_modified_weaning_cages as $cage ) : ?>
<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'weaning-cage', 'action' => 'view', 'id' => $cage['id'] ), null, true )?>"><?=$this->escape ( $cage['assigned_id'] )?></a></td>
		<td><a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'view', 'id' => $cage['litter_id'] ), null, true )?>"><?=$this->escape ( $cage['litter_assigned_id'] )?></a></td>
		<td><?=$this->escape ( $cage['sex'] )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($cage['weaned_on']) )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($cage['lastmodified']) )?></td>
	</tr>
<?php endforeach; ?>
</table>